version: '2'
services:
  payment-delivery-db:
    image: postgres:10.3-alpine
    hostname: payment-delivery-db
    mem_limit: 1g
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: payment-delivery-ms
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: payment-delivery-db
      PGDATA: /var/lib/postgresql/data/pgdata

    
